# Generated by Django 3.1.7 on 2021-04-05 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rss', models.CharField(max_length=255)),
                ('unread_pieces', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('key_words', models.TextField()),
                ('ignor_words', models.TextField(blank=True, default='')),
                ('unread_pieces', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published', models.DateTimeField()),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('chosen', models.BooleanField(default=False)),
                ('filtered', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('unread', models.BooleanField(default=True)),
                ('displayed', models.BooleanField(default=False)),
                ('topics_filtered', models.ManyToManyField(to='feed.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.website')),
            ],
        ),
    ]
