# Generated by Django 3.1.7 on 2021-04-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspiece',
            name='topics_assigned',
            field=models.ManyToManyField(related_name='assigned', to='feed.Topic'),
        ),
        migrations.AlterField(
            model_name='newspiece',
            name='topics_filtered',
            field=models.ManyToManyField(related_name='filtered', to='feed.Topic'),
        ),
    ]
