# Generated by Django 3.1.7 on 2021-04-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210405_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_upd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
